// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffasktgzaeqmyrzsiaqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmYXNrdGd6YWVxbXlyenNpYXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjE1MTAsImV4cCI6MjA2ODQzNzUxMH0.ebed_c5N43zIzZw7rijZW6hHBxBjT0Ie3KY9cWSni40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});